name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '[skip ci]')"
    permissions:
      contents: write       # Required for git push
      id-token: write       # Required for NPM Trusted Publishers (OIDC)
      pull-requests: write  # Required for release notes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for changelog generation

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install dependencies
      run: |
        rm -rf package-lock.json node_modules
        npm install

    - name: Debug npm auth context
      run: |
        echo "Has NODE_AUTH_TOKEN? ${NODE_AUTH_TOKEN:+yes}" 
        echo "Has NPM_TOKEN? ${NPM_TOKEN:+yes}"
        echo "NPM_CONFIG_USERCONFIG: ${NPM_CONFIG_USERCONFIG:-<none>}"
        if [ -n "${NPM_CONFIG_USERCONFIG:-}" ] && [ -f "$NPM_CONFIG_USERCONFIG" ]; then
          echo "----- $NPM_CONFIG_USERCONFIG -----"
          sed 's/_authToken=.*/_authToken=***REDACTED***/' "$NPM_CONFIG_USERCONFIG" || true
          echo "---------------------------------"
        fi

    - name: Release with Release It
      run: npx release-it --ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}