name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Add shebang to server.js
      run: |
        echo '#!/usr/bin/env node' | cat - dist/server.js > temp && mv temp dist/server.js
        chmod +x dist/server.js
        echo "✓ Added shebang to dist/server.js"

    - name: Verify package contents
      run: |
        echo "Package contents that will be published:"
        npm pack --dry-run
        echo ""
        echo "Verifying source files are excluded:"
        npm pack --dry-run | grep -q "src/" && echo "ERROR: Source files found!" && exit 1 || echo "✓ Source files excluded"

    - name: Update version if manual trigger
      if: github.event_name == 'workflow_dispatch'
      run: |
        npm version ${{ github.event.inputs.version }} --no-git-tag-version
        echo "Updated package.json to version ${{ github.event.inputs.version }}"

    - name: Publish to NPM
      run: |
        npm publish --access public
        echo "✓ Published @skippr/mcp-x-ray to NPM"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Verify publication
      run: |
        sleep 10  # Give NPM a moment to update
        npm view @skippr/mcp-x-ray version
        echo "✓ Package is available on NPM"

    - name: Create summary
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "## 📦 Published to NPM" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Package:** @skippr/mcp-x-ray" >> $GITHUB_STEP_SUMMARY
        echo "**Version:** $VERSION" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Installation" >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        echo "npm install -g @skippr/mcp-x-ray" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "[View on NPM](https://www.npmjs.com/package/@skippr/mcp-x-ray)" >> $GITHUB_STEP_SUMMARY