name: Test

on:
  push:
    branches: [main, develop, 'feature/**']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "github.event.head_commit.author.email != 'skippr-mcp-x-ray+bot@skippr.com'"

    strategy:
      matrix:
        node-version: [25.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Run test coverage
      if: matrix.node-version == '25.x'
      run: npm run test:coverage

    - name: Upload coverage reports
      if: matrix.node-version == '25.x'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/

    - name: Verify dist output
      run: |
        echo "Checking dist/ directory contents:"
        ls -la dist/
        echo "Checking if index.js exists:"
        test -f dist/index.js && echo "✓ dist/index.js exists" || exit 1
        echo "Verifying shebang in index.js:"
        head -1 dist/index.js | grep -q "^#!/usr/bin/env node" && echo "✓ Shebang present" || exit 1

    - name: Test package installation
      run: |
        npm pack
        npm install -g skippr-mcp-x-ray-*.tgz
        which skippr-mcp-x-ray || echo "Warning: Binary not found in PATH"